
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =            3594
     no. of nonzeroes in lower triangle of a =          198987
     no. of nonzeroes in the factor l        =          709320
     ratio of nonzeroes in factor (min/max)  =          0.7563
     number of super nodes                   =              94
     maximum order of a front matrix         =             399
     maximum size of a front matrix          =           79800
     maximum size of a front trapezoid       =           57009
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      1.4274D+08
     no. of floating point ops for solve     =      2.6147D+06
     ratio of flops for factor (min/max)     =          0.6944
     ratio of allocated memory (max/min)     =          1.2325
     number of positive pivots               =            3594
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000225
     time (cpu & wall) for ordering          =        0.000000        0.004363
     time (cpu & wall) for other matrix prep =        0.000000        0.001286
     time (cpu & wall) for value input       =        0.000000        0.000516
     time (cpu & wall) for matrix distrib.   =        0.000000        0.039178
     time (cpu & wall) for numeric factor    =        0.031250        0.186698
     computational rate (gflops) for factor  =        4.567614        0.764538

     no input or output performed

  Solver Memory allocated on core    0       =        4.297 MB
  Solver Memory allocated on core    1       =        3.487 MB
  Solver Memory allocated on core    2       =        3.962 MB
  Solver Memory allocated on core    3       =        3.553 MB
  Total Solver Memory allocated by all cores =       15.300 MB

